name: Meteor github actions

on:
  push:
    tags:
      - "deploy/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - name: Use Node.js 14.21.2
        with:
          node-version: "14.21.2"
      - run: "curl https://install.meteor.com/ | sh"
      - run: "meteor npm i"
      - run: "meteor test --once --driver-package meteortesting:mocha"
